### ISSUE TITLE
Custom CSS

### ISSUE THREAD

**Issue by siznax** [siznax/tanuki#3]
Have two CSS files that are initially empty, and supply selectors that users can style.
1. **custom.css** and selectors to specify background color/image and font style.
2. **entries.css** _should be empty_ by default and allow user-defined CSS, e.g.

``` css
img.book {
    margin-left:1em;
    margin-bottom:1em;
    float:right;
    width:240px;
}
```
